server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/restaurant_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: orderPlaced:com.foodDelivery.restaurant_service.dto.OrderPlacedEvent,orderAccepted:com.foodDelivery.restaurant_service.dto.OrderAcceptedEvent
    consumer:
      group-id: restaurant-service-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
        spring.json.type.mapping: orderPlaced:com.foodDelivery.restaurant_service.dto.OrderPlacedEvent,orderAccepted:com.foodDelivery.restaurant_service.dto.OrderAcceptedEvent

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

jwt:
  secret: ${JWT_SECRET:default-secret-key-for-jwt-signing-must-be-at-least-256-bits-long}
  expiration-ms: ${JWT_EXPIRATION:86400000}
